#!/usr/bin/env bash
# LimitX Nitro Enclave demo setup — run ONCE on the enclave EC2 host (Amazon Linux 2023).
#
# Builds the enclave .eif, records PCR0, installs parent services (vsock-proxy,
# enclave supervisor, HTTP→vsock bridge), and starts everything.
#
# !!! NOT for Windows / local laptop !!!
#    This needs nitro-cli, EnclaveOptions EC2, systemd, and a private VPC host.
#    From your Windows machine: deploy the nitro-enclave CloudFormation stack,
#    SSH into the instance, then run this script there.
#
# On the EC2 host (Amazon Linux 2023):
#   cd /path/to/repo
#   sudo AWS_REGION=eu-north-1 bash infra/nitro-enclave/deploy.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-eu-north-1}}"
OPT_ROOT="${LIMITX_OPT_ROOT:-/opt/limitx}"
EIF_DIR="${OPT_ROOT}/enclave"
PARENT_DIR="${OPT_ROOT}/parent"
ENV_FILE="/etc/limitx/enclave.env"
ENCLAVE_CID="${ENCLAVE_CID:-16}"
CPU_COUNT="${ENCLAVE_CPU_COUNT:-2}"
MEMORY_MIB="${ENCLAVE_MEMORY_MIB:-256}"

log() { echo "[deploy] $*"; }
die() { echo "[deploy] ERROR: $*" >&2; exit 1; }

# Refuse Windows / Git Bash / Cygwin — Nitro Enclaves are Linux EC2 only
uname_s="$(uname -s 2>/dev/null || echo unknown)"
case "${uname_s}" in
  MINGW*|MSYS*|CYGWIN*|Windows_NT)
    die "deploy.sh must run on the Nitro EC2 host (Amazon Linux 2023), not Windows.

  On your laptop (PowerShell):
    1. Deploy infra/nitro-enclave/nitro-enclave.yaml (see README)
    2. SSH to the instance private/public bastion path
    3. On the EC2 host:
         sudo AWS_REGION=${REGION} bash infra/nitro-enclave/deploy.sh

  Enabling Windows 'sudo' will not help — nitro-cli and enclaves are not available here."
    ;;
esac

if [[ ! -d /sys/module/nitro_enclaves ]] && ! command -v nitro-cli >/dev/null 2>&1; then
  die "nitro-cli / nitro_enclaves kernel module not found.
  This script only works on an EC2 instance with EnclaveOptions.Enabled=true
  (see infra/nitro-enclave/nitro-enclave.yaml)."
fi

[[ "$(id -u)" -eq 0 ]] || die "run as root on the EC2 host:  sudo bash infra/nitro-enclave/deploy.sh"

command -v docker >/dev/null || die "docker required"
command -v nitro-cli >/dev/null || die "nitro-cli required (aws-nitro-enclaves-cli)"
command -v python3 >/dev/null || die "python3 required"

# --- 1) Build enclave image + PCR0 ---
log "Building enclave EIF (this may take several minutes)…"
mkdir -p "${EIF_DIR}"
bash "${ROOT}/enclave-app/build-enclave.sh" "limitx-enclave-app:latest"
cp -f "${ROOT}/enclave-app/limitx-enclave-app.eif" "${EIF_DIR}/limitx-enclave-app.eif"
cp -f "${ROOT}/enclave-app/pcr0.txt" "${EIF_DIR}/pcr0.txt"
PCR0="$(tr -d '[:space:]' < "${EIF_DIR}/pcr0.txt")"
log "PCR0=${PCR0}"
log "Saved EIF → ${EIF_DIR}/limitx-enclave-app.eif"

# --- 2) Install parent tree ---
log "Installing parent services under ${PARENT_DIR}"
mkdir -p "${PARENT_DIR}" /etc/limitx /etc/nitro_enclaves
rsync -a --delete \
  --exclude 'proxy-service/target' \
  "${ROOT}/parent/" "${PARENT_DIR}/"

# vsock-proxy allowlist: KMS for this region ONLY
KMS_HOST="kms.${REGION}.amazonaws.com"
cat > "${PARENT_DIR}/vsock-proxy.yaml" <<EOF
# Generated by deploy.sh — do not add other destinations.
allow_list:
  - { address: ${KMS_HOST}, port: 443 }
EOF
cp -f "${PARENT_DIR}/vsock-proxy.yaml" /etc/nitro_enclaves/vsock-proxy.yaml
chmod 644 /etc/nitro_enclaves/vsock-proxy.yaml
log "vsock-proxy allowlist → only ${KMS_HOST}:443"

chmod +x "${PARENT_DIR}/start-enclave.sh"

# --- 3) Build & install parent HTTP→vsock proxy (Rust, matches enclave-app) ---
log "Building limitx-parent-proxy…"
if [[ -f "${PARENT_DIR}/proxy-service/Dockerfile" ]]; then
  docker build -t limitx-parent-proxy:latest "${PARENT_DIR}/proxy-service"
  # Extract binary from image
  CID="$(docker create limitx-parent-proxy:latest)"
  docker cp "${CID}:/usr/local/bin/limitx-parent-proxy" /usr/local/bin/limitx-parent-proxy
  docker rm "${CID}" >/dev/null
else
  die "proxy-service Dockerfile missing"
fi
chmod +x /usr/local/bin/limitx-parent-proxy

# --- 4) Environment for systemd ---
PRIVATE_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
cat > "${ENV_FILE}" <<EOF
AWS_REGION=${REGION}
AWS_DEFAULT_REGION=${REGION}
EIF_PATH=${EIF_DIR}/limitx-enclave-app.eif
ENCLAVE_CID=${ENCLAVE_CID}
ENCLAVE_CPU_COUNT=${CPU_COUNT}
ENCLAVE_MEMORY_MIB=${MEMORY_MIB}
ENCLAVE_VSOCK_PORT=5000
BIND_ADDR=0.0.0.0:8443
RUST_LOG=limitx_parent_proxy=info
EOF
chmod 644 "${ENV_FILE}"

# --- 5) systemd units ---
log "Installing systemd units"
cp -f "${PARENT_DIR}/systemd/limitx-vsock-proxy.service" /etc/systemd/system/
cp -f "${PARENT_DIR}/systemd/limitx-enclave.service" /etc/systemd/system/
cp -f "${PARENT_DIR}/systemd/limitx-parent-proxy.service" /etc/systemd/system/
# Patch vsock-proxy ExecStart region into unit Environment default
sed -i "s/Environment=AWS_REGION=.*/Environment=AWS_REGION=${REGION}/" \
  /etc/systemd/system/limitx-vsock-proxy.service

systemctl daemon-reload
systemctl enable limitx-vsock-proxy.service limitx-enclave.service limitx-parent-proxy.service

log "Starting vsock-proxy…"
systemctl restart limitx-vsock-proxy.service
sleep 1
systemctl is-active --quiet limitx-vsock-proxy.service || die "vsock-proxy failed — journalctl -u limitx-vsock-proxy"

log "Starting enclave supervisor…"
systemctl restart limitx-enclave.service
# give nitro-cli time to launch
for i in $(seq 1 30); do
  if nitro-cli describe-enclaves 2>/dev/null | grep -qi EnclaveCID; then
    break
  fi
  sleep 2
done
nitro-cli describe-enclaves || true

log "Starting parent HTTP proxy…"
systemctl restart limitx-parent-proxy.service
sleep 1
systemctl is-active --quiet limitx-parent-proxy.service || die "parent-proxy failed — journalctl -u limitx-parent-proxy"

# --- 6) Smoke health ---
HEALTH="$(curl -sf "http://127.0.0.1:8443/health" || true)"
log "health: ${HEALTH:-"(no response)"}"

cat <<EOF

============================================
 LimitX Nitro Enclave deploy complete
============================================
 PCR0:          ${PCR0}
 EIF:           ${EIF_DIR}/limitx-enclave-app.eif
 Parent URL:    http://${PRIVATE_IP:-<private-ip>}:8443
 vsock-proxy:   ${KMS_HOST}:443 ONLY
 Enclave CID:   ${ENCLAVE_CID}

 Next — SAM redeploy with:
   SigningMode=nitro-enclave
   EnclaveParentUrl=http://${PRIVATE_IP:-<private-ip>}:8443
   EnclaveImageSha384=${PCR0}
   NitroEnclaveInstanceRoleArn=<from nitro-enclave stack>
   NitroPrivateSubnetId=<from nitro-enclave stack>
   NitroLambdaSecurityGroupId=<SG that can reach :8443>

 Sid SignOnlyWithEnclaveImageAttestation binds kms:RecipientAttestation:ImageSha384
 to PCR0 above. Flip SigningMode=lambda-kms for live-demo fallback.
 (see enclave-app/kms-pcr0-policy.example.json).
============================================
EOF
